FAQ Administrator
0x7d8/addon-bot pull request #1
Opened 2024-10-10 15:17 UTC by Anthony01M

Allows administrators to create, remove or update a FAQ.

2024-10-10 15:21 UTC, 0x7d8 requested changes

2024-10-10 15:21 UTC, 0x7d8 commented on server/src/bot/commands/faq-admin.ts
> +            }
leave an empty line

2024-10-10 15:21 UTC, 0x7d8 commented on server/src/bot/commands/faq-admin.ts
> +                const data = await ctx.database.select({
dont select unnecessary data, just select id here

2024-10-10 15:21 UTC, 0x7d8 commented on server/src/bot/commands/faq-admin.ts
> +            }
empty line

2024-10-10 15:21 UTC, 0x7d8 commented on server/src/bot/modals/faq/add-faq.ts
> +        if (!ctx.interaction.guild) return
empty line

2024-10-10 15:21 UTC, 0x7d8 commented on server/src/bot/modals/faq/add-faq.ts
> +        const content = ctx.interaction.fields.getTextInputValue('content')
empty line

2024-10-10 15:21 UTC, 0x7d8 commented on server/src/bot/modals/faq/add-faq.ts
> +        const title = ctx.interaction.fields.getTextInputValue('title')
join these variables with commas, not seperate const declarations

2024-10-10 15:21 UTC, 0x7d8 commented on server/src/bot/modals/faq/update-faq-content.ts
> +        const content = ctx.interaction.fields.getTextInputValue('content')
empty line

2024-10-10 15:21 UTC, 0x7d8 commented on server/src/bot/modals/faq/update-faq-content.ts
> +        if (!ctx.interaction.guild) return
empty line

2024-10-10 15:21 UTC, 0x7d8 commented on server/src/bot/modals/faq/update-faq-content.ts
> +            .where(eq(ctx.database.schema.faqs.id, id))
empty line

2024-10-10 15:21 UTC, 0x7d8 commented on server/src/bot/modals/faq/update-faq-title.ts
> +                .where(eq(ctx.database.schema.faqs.id, id))
empty line

2024-10-10 15:21 UTC, 0x7d8 commented on server/src/bot/modals/faq/update-faq-title.ts
> +        if (!ctx.interaction.guild) return
empty line

2024-10-10 15:31 UTC, 0x7d8 commented on server/src/bot/modals/faq/add-faq.ts
> +        content = ctx.interaction.fields.getTextInputValue('content')
add a tab before content

2024-10-11 10:10 UTC, 0x7d8 commented
@Anthony01M for editing, scrap the buttons and just show a modal with title and content but use .setValue to prefill the values with the current state

2024-10-11 10:11 UTC, Anthony01M commented
Made it like this so that in case we want to edit just the title or just
the content

On Fri, Oct 11, 2024, 1:10 PM Robert Jansen ***@***.***>
wrote:

> @Anthony01M <https://github.com/Anthony01M> for editing, scrap the
> buttons and just show a modal with title and content but use .setValue to
> prefill the values with the current state
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/0x7d8/addon-bot/pull/1#issuecomment-2407085515>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AICPHKQ7MS4R2RE6WPC77DDZ26PZNAVCNFSM6AAAAABPXBBRNGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBXGA4DKNJRGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-11 10:13 UTC, 0x7d8 commented
if you prefill the modal with values that same thing can be achieved better

2024-10-11 10:17 UTC, Anthony01M commented
Or we could keep same way and just prefill the details, wouldn't that also
work?

On Fri, Oct 11, 2024, 1:13 PM Robert Jansen ***@***.***>
wrote:

> if you prefill the modal with values that same thing can be achieved better
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/0x7d8/addon-bot/pull/1#issuecomment-2407091038>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AICPHKRFWTND2NRLRMLF3ILZ26QFNAVCNFSM6AAAAABPXBBRNGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBXGA4TCMBTHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-11 13:21 UTC, 0x7d8 commented
please make sure you use tabs, not spaces as identation

2024-10-11 16:45 UTC, merged